import { AboutSlint, VerticalBox, ListView } from "std-widgets.slint";


struct LogEntryUI {
    text: string,
    color: color
}
export component Launcher inherits Window {
    preferred-width: 1920px; 
    preferred-height: 1080px;
    title: "Launcher |";
    
    in property <[LogEntryUI]> console_logs: [
        {text: "Console prête", color: #ffffff},
        {text: "Console prête", color: #ffffff},
        {text: "Console prête", color: #ffffff},
        {text: "Console prête", color: #ffffff},
        {text: "Console prête", color: #ffffff},
        {text: "Console prête", color: #ffffff},
        {text: "Console prête", color: #ffffff},
        {text: "Console prête", color: #ffffff},
        {text: "Ceci est <span style='color: red;'>rouge</span> et ceci est <span style='color: green;'>vert</span>", color: #ffffff},
    ];

    VerticalLayout {
        padding: 20px;
        spacing: 20px;

        Rectangle {
            background: #1e1e1e; // Terminal background,
            border-radius: 4px;
            clip: true;

            ListView {
                for entry in root.console_logs : Text {
                    text: entry.text;
                    color: entry.color;
                    font-family: "Monospace";
                    font-size: 14px;
                    format: rich;
                }
            }
        }
    }
    
}
